---
title: "CURSO R"
author: "Rafael de Cordova Martins e Douglas Linzmeyer de Araujo Goes"
date: "02/07/2020"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, cache=TRUE, echo=TRUE, warning=FALSE}

  # Check if the packages that we need are installed
  want = c("tidyverse", "data.table", "readr", "stringr", "zoo", "plyr", "dplyr", "COVID19", "usethis", "tidyr")
  have = want %in% rownames(installed.packages())
  # Install the packages that we miss
  if ( any(!have) ) { install.packages( want[!have] ) }
  # Load the packages
  junk <- lapply(want, library, character.only = T)
  # Remove the objects we created
  rm(have, want, junk)
  
# import packages

#CARREGAR-PACOTES
library(tidyverse)
library(COVID19)
library(dplyr)
library(plotly)
library(readr)
library(data.table)
library(pipeR)
library(zoo)
library(plyr)
library(tidyr)

  usethis::use_git_config(user.name = "RafaMars53", 
                          user.email = "rafaellmartins5353@gmail.com") 
  usethis::browse_github_token()
  
  GITHUB_PAT= "b7c42a988f46512af078f39459cbb97e6a7e962d"




```

```{r database, cache=TRUE, echo=TRUE}
#IMPORTAR A DATA-BASE
url = "https://data.brasil.io/dataset/covid19/caso.csv.gz"

  # CRIAR ARQUIVO TEMP
  tmp = tempfile()
  
  # DOWNLOAD DO ARQUIVO
  download.file(url,tmp)
  
  # IMPORTANDO DATA BASE
  dcovid19 =   read_csv(gzfile(tmp),
                        col_types = cols(date = col_date(format = "%Y-%m-%d")), 
                        locale = locale(decimal_mark = ",", grouping_mark = ".", 
                                        encoding = "UTF-8"))
  dcitypr = dcovid19 %>% filter(state == "PR" & place_type == "city" & date > "2020-03-15") %>%
    mutate(select = case_when(city_ibge_code == 4104808 ~ "Cascavel",
                              city_ibge_code == 4105805 ~ "Colombo",
                              city_ibge_code == 4106902 ~ "Curitiba",
                              city_ibge_code == 4108304 ~ "Foz do Igua?u",
                              city_ibge_code == 4109401 ~ "Guarapuava",
                              city_ibge_code == 4113700 ~ "Londrina",
                              city_ibge_code == 4115200 ~ "Maring?",
                              city_ibge_code == 4118204 ~ "Paranagu?",
                              city_ibge_code == 4119905 ~ "Ponta Grossa",
                              city_ibge_code == 4125506 ~ "S?o Jos? dos Pinhais",
                              TRUE ~ "Outras cidades")) %>%
    arrange(desc(date)) %>%
    group_by(date, select) %>%
    dplyr::summarize(confirmed = sum(confirmed),
                     deaths = sum(deaths),
                     population = sum(estimated_population_2019)) 

    # TIME LAG
  setDT(dcitypr)[, deaths_1 := shift(deaths, fill=0), by = select]
  setDT(dcitypr)[, confirmed_1 := shift(confirmed, fill=0), by = select]
  
  #DCITYPR - DATA 
  dcitypr = dcitypr %>% mutate(deaths_new = deaths - deaths_1,
                               confirmed_new = confirmed - confirmed_1) %>%
    ungroup() %>% select(date, select, confirmed, confirmed_new, deaths, deaths_new) %>% 
    arrange(desc(date))

gdeaths = dcovid19 %>% 
  filter(state == c("PR", "SP"),
         place_type == "state")

g = ggplot(data=gdeaths, aes(x=date, y=confirmed, group = state)) + 
      geom_line() +
      geom_point(aes(x=date, y=confirmed, color = state))
  
g + labs(title="Evolução das ocorrências (casos)", x="Período", y="Confirmados") 
g + xlab(NULL) + ylab(NULL)

g + theme(panel.grid.major = element_line(colour = "black"))
g + theme(panel.grid.major = element_line(size = 2))
g + theme(panel.grid.major = element_line(linetype = "dotted"))

g + theme(plot.background = element_rect(fill = "grey80", colour = NA))
g + theme(plot.background = element_rect(colour = "red", size = 2))
g + theme(panel.background = element_rect(fill = "linen"))

last_plot() + theme(panel.grid.minor = element_blank())
last_plot() + theme(panel.grid.major = element_blank())
last_plot() + theme(panel.background = element_blank())
last_plot() + theme(axis.title.x = element_blank(),  
                   axis.title.y = element_blank())

g + theme(aspect.ratio = 9 / 16) # Wide screen
g + theme(aspect.ratio = 2 / 1) # Long and skiny
g + theme(aspect.ratio = 1)

g + theme(legend.position = "none") 
g + theme(legend.position="top")
g + theme(legend.position="bottom")


g

```
